
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.analizadores;

/** CUP generated class containing symbol constants. */
public class ParserConsultaSym {
  /* terminals */
  public static final int COMA = 5;
  public static final int MENOR = 3;
  public static final int P_COMA = 6;
  public static final int EOF = 0;
  public static final int VIS_SITIOS = 10;
  public static final int CONSULTAR = 9;
  public static final int COMPONENTE = 13;
  public static final int ID = 8;
  public static final int MAYOR = 4;
  public static final int IGUAL = 2;
  public static final int error = 1;
  public static final int TODOS = 14;
  public static final int PAG_POPULARES = 12;
  public static final int VIS_PAGINA = 11;
  public static final int PATH = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "COMA",
  "P_COMA",
  "PATH",
  "ID",
  "CONSULTAR",
  "VIS_SITIOS",
  "VIS_PAGINA",
  "PAG_POPULARES",
  "COMPONENTE",
  "TODOS"
  };
}

