
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.analizadores;

/** CUP generated class containing symbol constants. */
public class ParserXMLSym {
  /* terminals */
  public static final int MENOR = 3;
  public static final int SLASH = 7;
  public static final int ACCION = 10;
  public static final int ETIQUETAS = 17;
  public static final int ETIQUETA = 16;
  public static final int ID = 19;
  public static final int COMA = 5;
  public static final int NOMBRE = 15;
  public static final int MAYOR = 4;
  public static final int EOF = 0;
  public static final int PARAMETROS = 12;
  public static final int ATRIBUTOS = 13;
  public static final int error = 1;
  public static final int EQ = 2;
  public static final int P_COMA = 6;
  public static final int ATRIBUTO = 14;
  public static final int COR_DER = 9;
  public static final int PARAMETRO = 11;
  public static final int VALOR = 18;
  public static final int COR_IZ = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQ",
  "MENOR",
  "MAYOR",
  "COMA",
  "P_COMA",
  "SLASH",
  "COR_IZ",
  "COR_DER",
  "ACCION",
  "PARAMETRO",
  "PARAMETROS",
  "ATRIBUTOS",
  "ATRIBUTO",
  "NOMBRE",
  "ETIQUETA",
  "ETIQUETAS",
  "VALOR",
  "ID"
  };
}

